#include <MetaNN/layers/principal/math/abs_layer.h>
#include <MetaNN/layers/principal/math/acos_layer.h>
#include <MetaNN/layers/principal/math/acosh_layer.h>
#include <MetaNN/layers/principal/math/add_layer.h>
#include <MetaNN/layers/principal/math/asin_layer.h>
#include <MetaNN/layers/principal/math/asinh_layer.h>
#include <MetaNN/layers/principal/math/cos_layer.h>
#include <MetaNN/layers/principal/math/multiply_layer.h>
#include <MetaNN/layers/principal/math/sigmoid_layer.h>
#include <MetaNN/layers/principal/math/sin_layer.h>
#include <MetaNN/layers/principal/math/square_layer.h>
#include <MetaNN/layers/principal/math/substract_layer.h>
#include <MetaNN/layers/principal/math/tan_layer.h>
#include <MetaNN/layers/principal/math/tanh_layer.h>